version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=https://dev.lan.ddnsgeek.com
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
#      - "traefik.docker.network=proxy"
      - "traefik.http.routers.dev.rule=Host(`dev.lan.ddnsgeek.com`)"
      - "traefik.http.routers.dev.entrypoints=websecure"
      - "traefik.http.routers.dev.tls=true"
      - "traefik.http.routers.dev.tls.certresolver=myresolver"
      - "traefik.http.services.dev.loadbalancer.server.port=3000"
      - "io.portainer.accesscontrol.public"
      - "traefik.http.routers.dev.middlewares=error-pages-middleware"
    networks:
#      - proxy
      - traefik_default
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_PATH=app/app.db  # or your production DB
      - JWT_SECRET_KEY="${JWT_SECRET_KEY}"
      - ORS_API_KEY="${ORS_API_KEY}"
    volumes:
      - ./data/app.db:/data/app.db  # If using SQLite
    networks:
#      - proxy
      - traefik_default

#volumes:
#  gitea_data:

networks:
  traefik_default:
    external: true