"""Update user schema

Revision ID: 08f689af215b
Revises: 57128b4acc27
Create Date: 2025-08-11 08:03:20.619613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08f689af215b'
down_revision = '57128b4acc27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
