"""Update user schema

Revision ID: 2f56f1a0ff35
Revises: 421d3db8d5bd
Create Date: 2025-08-07 14:41:01.962407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f56f1a0ff35'
down_revision = '421d3db8d5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
