"""user service fix

Revision ID: 3667fe8a73d2
Revises: 08f689af215b
Create Date: 2025-08-11 08:15:36.281416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3667fe8a73d2'
down_revision = '08f689af215b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
