"""Update user schema

Revision ID: 3b91160c80d6
Revises: 2f56f1a0ff35
Create Date: 2025-08-10 14:45:12.696528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b91160c80d6'
down_revision = '2f56f1a0ff35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
