"""Rename tables and update schema

Revision ID: 410a07eed5b6
Revises: 54aae5235202
Create Date: 2025-08-03 22:33:31.891097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410a07eed5b6'
down_revision = '54aae5235202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
