"""Update user schema

Revision ID: 421d3db8d5bd
Revises: b9516c750b29
Create Date: 2025-08-07 14:33:25.151974

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "421d3db8d5bd"
down_revision = "b9516c750b29"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_approved")
        batch_op.drop_column("role")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("role", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("is_approved", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
