"""Rename tables and update schema

Revision ID: 54aae5235202
Revises: e616cf383100
Create Date: 2025-08-03 22:30:20.014796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54aae5235202'
down_revision = 'e616cf383100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
