"""Update user schema

Revision ID: 57128b4acc27
Revises: 3b91160c80d6
Create Date: 2025-08-10 15:40:48.908894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57128b4acc27'
down_revision = '3b91160c80d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
