"""Initial ride‑booking schema

Revision ID: 88eb19aeefe3
Revises: 
Create Date: 2025-08-03 18:55:31.515170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88eb19aeefe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
