"""change account mode to bool

Revision ID: e0c95c7de469
Revises: f3110ce62ca7
Create Date: 2025-08-17 18:08:34.364723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c95c7de469'
down_revision = 'f3110ce62ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
