"""Initial ride‑booking schema

Revision ID: e616cf383100
Revises: 88eb19aeefe3
Create Date: 2025-08-03 18:58:04.424070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e616cf383100'
down_revision = '88eb19aeefe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
