"""update settings tables

Revision ID: f3110ce62ca7
Revises: 3667fe8a73d2
Create Date: 2025-08-17 16:51:31.929950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3110ce62ca7'
down_revision = '3667fe8a73d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_mode', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('per_minute_rate', sa.Float(), nullable=False))
        batch_op.alter_column('google_maps_api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('flagfall',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('per_km_rate',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_admin_config_id'))
        batch_op.drop_column('per_min_rate')
        batch_op.drop_column('allow_public_registration')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('dropoff_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_bookings_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_id'), ['id'], unique=False)
        batch_op.alter_column('time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('dropoff_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('pickup_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('admin_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_public_registration', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('per_min_rate', sa.FLOAT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_config_id'), ['id'], unique=False)
        batch_op.alter_column('per_km_rate',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('flagfall',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('google_maps_api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('per_minute_rate')
        batch_op.drop_column('account_mode')

    # ### end Alembic commands ###
